# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'habitat_tracking.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Habitat_tracking(object):
    def setupUi(self, Habitat_tracking):
        Habitat_tracking.setObjectName("Habitat_tracking")
        Habitat_tracking.resize(929, 561)
        self.centralwidget = QtWidgets.QWidget(Habitat_tracking)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 931, 781))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 521, 521))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("habitat75.png"))
        self.label.setObjectName("label")
        self.pb_tunnel_1 = QtWidgets.QPushButton(self.tab_2)
        self.pb_tunnel_1.setEnabled(False)
        self.pb_tunnel_1.setGeometry(QtCore.QRect(86, 49, 87, 40))
        self.pb_tunnel_1.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.pb_tunnel_1.setObjectName("pb_tunnel_1")
        self.pb_tunnel_2 = QtWidgets.QPushButton(self.tab_2)
        self.pb_tunnel_2.setEnabled(False)
        self.pb_tunnel_2.setGeometry(QtCore.QRect(214, 49, 87, 40))
        self.pb_tunnel_2.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.pb_tunnel_2.setObjectName("pb_tunnel_2")
        self.pb_tunnel_3 = QtWidgets.QPushButton(self.tab_2)
        self.pb_tunnel_3.setEnabled(False)
        self.pb_tunnel_3.setGeometry(QtCore.QRect(341, 177, 87, 40))
        self.pb_tunnel_3.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.pb_tunnel_3.setObjectName("pb_tunnel_3")
        self.pb_tunnel_4 = QtWidgets.QPushButton(self.tab_2)
        self.pb_tunnel_4.setEnabled(False)
        self.pb_tunnel_4.setGeometry(QtCore.QRect(128, 346, 131, 40))
        self.pb_tunnel_4.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.pb_tunnel_4.setObjectName("pb_tunnel_4")
        self.pb_tunnel_5 = QtWidgets.QPushButton(self.tab_2)
        self.pb_tunnel_5.setEnabled(False)
        self.pb_tunnel_5.setGeometry(QtCore.QRect(87, 304, 87, 40))
        self.pb_tunnel_5.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.pb_tunnel_5.setObjectName("pb_tunnel_5")
        self.pb_tunnel_6 = QtWidgets.QPushButton(self.tab_2)
        self.pb_tunnel_6.setEnabled(False)
        self.pb_tunnel_6.setGeometry(QtCore.QRect(214, 304, 87, 40))
        self.pb_tunnel_6.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.pb_tunnel_6.setObjectName("pb_tunnel_6")
        self.pb_tunnel_8 = QtWidgets.QPushButton(self.tab_2)
        self.pb_tunnel_8.setEnabled(False)
        self.pb_tunnel_8.setGeometry(QtCore.QRect(87, 431, 87, 40))
        self.pb_tunnel_8.setStyleSheet("background-color: rgb(193, 193, 193);\n"
"")
        self.pb_tunnel_8.setObjectName("pb_tunnel_8")
        self.pb_tunnel_9 = QtWidgets.QPushButton(self.tab_2)
        self.pb_tunnel_9.setEnabled(False)
        self.pb_tunnel_9.setGeometry(QtCore.QRect(214, 431, 87, 40))
        self.pb_tunnel_9.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.pb_tunnel_9.setObjectName("pb_tunnel_9")
        self.pb_tunnel_7 = QtWidgets.QPushButton(self.tab_2)
        self.pb_tunnel_7.setEnabled(False)
        self.pb_tunnel_7.setGeometry(QtCore.QRect(128, 473, 131, 40))
        self.pb_tunnel_7.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.pb_tunnel_7.setObjectName("pb_tunnel_7")
        self.pb_start = QtWidgets.QPushButton(self.tab_2)
        self.pb_start.setGeometry(QtCore.QRect(550, 140, 81, 41))
        self.pb_start.setObjectName("pb_start")
        self.pb_stop = QtWidgets.QPushButton(self.tab_2)
        self.pb_stop.setEnabled(False)
        self.pb_stop.setGeometry(QtCore.QRect(810, 140, 81, 41))
        self.pb_stop.setObjectName("pb_stop")
        self.pb_pause = QtWidgets.QPushButton(self.tab_2)
        self.pb_pause.setEnabled(False)
        self.pb_pause.setGeometry(QtCore.QRect(680, 140, 81, 41))
        self.pb_pause.setObjectName("pb_pause")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(550, 84, 111, 16))
        self.label_3.setObjectName("label_3")
        self.sb_speed = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.sb_speed.setGeometry(QtCore.QRect(663, 80, 42, 22))
        self.sb_speed.setDecimals(1)
        self.sb_speed.setMaximum(10.0)
        self.sb_speed.setSingleStep(0.1)
        self.sb_speed.setProperty("value", 1.0)
        self.sb_speed.setObjectName("sb_speed")
        self.txt_animal_id = QtWidgets.QTextEdit(self.tab_2)
        self.txt_animal_id.setGeometry(QtCore.QRect(610, 10, 291, 31))
        self.txt_animal_id.setObjectName("txt_animal_id")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(550, 20, 61, 16))
        self.label_9.setObjectName("label_9")
        self.pb_export_excel = QtWidgets.QPushButton(self.tab_2)
        self.pb_export_excel.setEnabled(False)
        self.pb_export_excel.setGeometry(QtCore.QRect(550, 270, 141, 41))
        self.pb_export_excel.setObjectName("pb_export_excel")
        self.lcdTime = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdTime.setGeometry(QtCore.QRect(550, 210, 161, 31))
        self.lcdTime.setDigitCount(9)
        self.lcdTime.setObjectName("lcdTime")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(721, 220, 121, 16))
        self.label_5.setObjectName("label_5")
        self.label.raise_()
        self.pb_start.raise_()
        self.pb_stop.raise_()
        self.pb_pause.raise_()
        self.label_3.raise_()
        self.sb_speed.raise_()
        self.txt_animal_id.raise_()
        self.label_9.raise_()
        self.pb_export_excel.raise_()
        self.pb_tunnel_1.raise_()
        self.pb_tunnel_2.raise_()
        self.pb_tunnel_4.raise_()
        self.pb_tunnel_3.raise_()
        self.pb_tunnel_5.raise_()
        self.pb_tunnel_6.raise_()
        self.pb_tunnel_7.raise_()
        self.pb_tunnel_8.raise_()
        self.pb_tunnel_9.raise_()
        self.lcdTime.raise_()
        self.label_5.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(770, 167, 47, 13))
        self.label_24.setObjectName("label_24")
        self.ButtonRunAll = QtWidgets.QPushButton(self.tab)
        self.ButtonRunAll.setGeometry(QtCore.QRect(750, 40, 70, 51))
        self.ButtonRunAll.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ButtonRunAll.setObjectName("ButtonRunAll")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(830, 182, 41, 16))
        self.label_18.setObjectName("label_18")
        self.Button2PDF = QtWidgets.QPushButton(self.tab)
        self.Button2PDF.setGeometry(QtCore.QRect(796, 203, 41, 19))
        self.Button2PDF.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Button2PDF.setObjectName("Button2PDF")
        self.frame_Control = QtWidgets.QFrame(self.tab)
        self.frame_Control.setGeometry(QtCore.QRect(10, 130, 631, 101))
        self.frame_Control.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Control.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_Control.setObjectName("frame_Control")
        self.ButtonAddSecondExcel = QtWidgets.QPushButton(self.frame_Control)
        self.ButtonAddSecondExcel.setGeometry(QtCore.QRect(60, 19, 111, 31))
        self.ButtonAddSecondExcel.setObjectName("ButtonAddSecondExcel")
        self.ButtonDeleteSecondExcel = QtWidgets.QPushButton(self.frame_Control)
        self.ButtonDeleteSecondExcel.setGeometry(QtCore.QRect(59, 51, 112, 31))
        self.ButtonDeleteSecondExcel.setObjectName("ButtonDeleteSecondExcel")
        self.label_6 = QtWidgets.QLabel(self.frame_Control)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 41, 31))
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setObjectName("label_6")
        self.labelSecondFile = QtWidgets.QLabel(self.frame_Control)
        self.labelSecondFile.setGeometry(QtCore.QRect(190, 30, 411, 41))
        self.labelSecondFile.setText("")
        self.labelSecondFile.setObjectName("labelSecondFile")
        self.frame_Experimental = QtWidgets.QFrame(self.tab)
        self.frame_Experimental.setGeometry(QtCore.QRect(10, 20, 631, 101))
        self.frame_Experimental.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Experimental.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_Experimental.setObjectName("frame_Experimental")
        self.ButtonAddFirstExcel = QtWidgets.QPushButton(self.frame_Experimental)
        self.ButtonAddFirstExcel.setGeometry(QtCore.QRect(60, 19, 111, 31))
        self.ButtonAddFirstExcel.setObjectName("ButtonAddFirstExcel")
        self.ButtonDeleteFirstExcel = QtWidgets.QPushButton(self.frame_Experimental)
        self.ButtonDeleteFirstExcel.setGeometry(QtCore.QRect(59, 51, 112, 31))
        self.ButtonDeleteFirstExcel.setObjectName("ButtonDeleteFirstExcel")
        self.label_2 = QtWidgets.QLabel(self.frame_Experimental)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 41, 31))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setObjectName("label_2")
        self.labelFirstFile = QtWidgets.QLabel(self.frame_Experimental)
        self.labelFirstFile.setGeometry(QtCore.QRect(200, 30, 411, 41))
        self.labelFirstFile.setText("")
        self.labelFirstFile.setObjectName("labelFirstFile")
        self.Button2PNG = QtWidgets.QPushButton(self.tab)
        self.Button2PNG.setGeometry(QtCore.QRect(857, 203, 41, 19))
        self.Button2PNG.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Button2PNG.setObjectName("Button2PNG")
        self.ButtonClearFigures = QtWidgets.QPushButton(self.tab)
        self.ButtonClearFigures.setGeometry(QtCore.QRect(670, 185, 81, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ButtonClearFigures.setPalette(palette)
        self.ButtonClearFigures.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ButtonClearFigures.setObjectName("ButtonClearFigures")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(660, 180, 251, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_montage = QtWidgets.QFrame(self.tab)
        self.frame_montage.setGeometry(QtCore.QRect(30, 374, 241, 21))
        self.frame_montage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_montage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_montage.setObjectName("frame_montage")
        self.frame_2.raise_()
        self.label_24.raise_()
        self.ButtonRunAll.raise_()
        self.label_18.raise_()
        self.Button2PDF.raise_()
        self.frame_Control.raise_()
        self.frame_Experimental.raise_()
        self.Button2PNG.raise_()
        self.ButtonClearFigures.raise_()
        self.frame_montage.raise_()
        self.tabWidget.addTab(self.tab, "")
        Habitat_tracking.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Habitat_tracking)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 21))
        self.menubar.setObjectName("menubar")
        Habitat_tracking.setMenuBar(self.menubar)

        self.retranslateUi(Habitat_tracking)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Habitat_tracking)

    def retranslateUi(self, Habitat_tracking):
        _translate = QtCore.QCoreApplication.translate
        Habitat_tracking.setWindowTitle(_translate("Habitat_tracking", "MainWindow"))
        self.pb_tunnel_1.setToolTip(_translate("Habitat_tracking", "<html><head/><body><p><br/></p></body></html>"))
        self.pb_tunnel_1.setText(_translate("Habitat_tracking", "1"))
        self.pb_tunnel_2.setToolTip(_translate("Habitat_tracking", "<html><head/><body><p><br/></p></body></html>"))
        self.pb_tunnel_2.setText(_translate("Habitat_tracking", "2"))
        self.pb_tunnel_3.setToolTip(_translate("Habitat_tracking", "<html><head/><body><p><br/></p></body></html>"))
        self.pb_tunnel_3.setText(_translate("Habitat_tracking", "3"))
        self.pb_tunnel_4.setToolTip(_translate("Habitat_tracking", "<html><head/><body><p><br/></p></body></html>"))
        self.pb_tunnel_4.setText(_translate("Habitat_tracking", "4"))
        self.pb_tunnel_5.setToolTip(_translate("Habitat_tracking", "<html><head/><body><p><br/></p></body></html>"))
        self.pb_tunnel_5.setText(_translate("Habitat_tracking", "5"))
        self.pb_tunnel_6.setToolTip(_translate("Habitat_tracking", "<html><head/><body><p><br/></p></body></html>"))
        self.pb_tunnel_6.setText(_translate("Habitat_tracking", "6"))
        self.pb_tunnel_8.setToolTip(_translate("Habitat_tracking", "<html><head/><body><p><br/></p></body></html>"))
        self.pb_tunnel_8.setText(_translate("Habitat_tracking", "8"))
        self.pb_tunnel_9.setToolTip(_translate("Habitat_tracking", "<html><head/><body><p><br/></p></body></html>"))
        self.pb_tunnel_9.setText(_translate("Habitat_tracking", "9"))
        self.pb_tunnel_7.setToolTip(_translate("Habitat_tracking", "<html><head/><body><p><br/></p></body></html>"))
        self.pb_tunnel_7.setText(_translate("Habitat_tracking", "7"))
        self.pb_start.setText(_translate("Habitat_tracking", "START"))
        self.pb_stop.setText(_translate("Habitat_tracking", "FINISH"))
        self.pb_pause.setText(_translate("Habitat_tracking", "PAUSE"))
        self.label_3.setText(_translate("Habitat_tracking", "Recording speed"))
        self.label_9.setText(_translate("Habitat_tracking", "Animal ID"))
        self.pb_export_excel.setText(_translate("Habitat_tracking", "Export to Excel"))
        self.label_5.setText(_translate("Habitat_tracking", "( H : MM : SS: MS )"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Habitat_tracking", "Tunnels"))
        self.label_24.setText(_translate("Habitat_tracking", "FIGURES"))
        self.ButtonRunAll.setText(_translate("Habitat_tracking", "RUN (ALL)"))
        self.label_18.setText(_translate("Habitat_tracking", "Export"))
        self.Button2PDF.setText(_translate("Habitat_tracking", "PDF"))
        self.ButtonAddSecondExcel.setText(_translate("Habitat_tracking", "Add excel file"))
        self.ButtonDeleteSecondExcel.setText(_translate("Habitat_tracking", "Delete"))
        self.label_6.setText(_translate("Habitat_tracking", "2"))
        self.ButtonAddFirstExcel.setText(_translate("Habitat_tracking", "Add excel file"))
        self.ButtonDeleteFirstExcel.setText(_translate("Habitat_tracking", "Delete"))
        self.label_2.setText(_translate("Habitat_tracking", "1"))
        self.Button2PNG.setText(_translate("Habitat_tracking", "PNG"))
        self.ButtonClearFigures.setText(_translate("Habitat_tracking", "Close All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Habitat_tracking", "Tracking Analysis"))

