# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w_coincidencies.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_w_coincidencies(object):
    def setupUi(self, w_coincidencies):
        w_coincidencies.setObjectName("w_coincidencies")
        w_coincidencies.resize(643, 229)
        self.centralwidget = QtWidgets.QWidget(w_coincidencies)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 931, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(480, 101, 47, 13))
        self.label_24.setObjectName("label_24")
        self.ButtonRunAll = QtWidgets.QPushButton(self.tab)
        self.ButtonRunAll.setGeometry(QtCore.QRect(220, 116, 70, 51))
        self.ButtonRunAll.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ButtonRunAll.setObjectName("ButtonRunAll")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(540, 117, 41, 16))
        self.label_18.setObjectName("label_18")
        self.Button2PDF = QtWidgets.QPushButton(self.tab)
        self.Button2PDF.setGeometry(QtCore.QRect(506, 138, 41, 19))
        self.Button2PDF.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Button2PDF.setObjectName("Button2PDF")
        self.frame_Experimental = QtWidgets.QFrame(self.tab)
        self.frame_Experimental.setGeometry(QtCore.QRect(10, 20, 611, 71))
        self.frame_Experimental.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Experimental.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_Experimental.setObjectName("frame_Experimental")
        self.ButtonSelectFolder = QtWidgets.QPushButton(self.frame_Experimental)
        self.ButtonSelectFolder.setGeometry(QtCore.QRect(9, 19, 81, 31))
        self.ButtonSelectFolder.setObjectName("ButtonSelectFolder")
        self.ButDelFile = QtWidgets.QPushButton(self.frame_Experimental)
        self.ButDelFile.setGeometry(QtCore.QRect(550, 20, 51, 31))
        self.ButDelFile.setObjectName("ButDelFile")
        self.labelFileSelected = QtWidgets.QLabel(self.frame_Experimental)
        self.labelFileSelected.setGeometry(QtCore.QRect(100, 19, 441, 31))
        self.labelFileSelected.setText("")
        self.labelFileSelected.setObjectName("labelFileSelected")
        self.Button2PNG = QtWidgets.QPushButton(self.tab)
        self.Button2PNG.setGeometry(QtCore.QRect(567, 138, 41, 19))
        self.Button2PNG.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.Button2PNG.setObjectName("Button2PNG")
        self.ButtonClearFigures = QtWidgets.QPushButton(self.tab)
        self.ButtonClearFigures.setGeometry(QtCore.QRect(380, 120, 81, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ButtonClearFigures.setPalette(palette)
        self.ButtonClearFigures.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ButtonClearFigures.setObjectName("ButtonClearFigures")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(370, 114, 251, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.label_24.raise_()
        self.ButtonRunAll.raise_()
        self.label_18.raise_()
        self.Button2PDF.raise_()
        self.frame_Experimental.raise_()
        self.Button2PNG.raise_()
        self.ButtonClearFigures.raise_()
        self.tabWidget.addTab(self.tab, "")
        w_coincidencies.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(w_coincidencies)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 21))
        self.menubar.setObjectName("menubar")
        w_coincidencies.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(w_coincidencies)
        self.statusbar.setObjectName("statusbar")
        w_coincidencies.setStatusBar(self.statusbar)

        self.retranslateUi(w_coincidencies)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(w_coincidencies)

    def retranslateUi(self, w_coincidencies):
        _translate = QtCore.QCoreApplication.translate
        w_coincidencies.setWindowTitle(_translate("w_coincidencies", "MainWindow"))
        self.label_24.setText(_translate("w_coincidencies", "FIGURES"))
        self.ButtonRunAll.setText(_translate("w_coincidencies", "RUN"))
        self.label_18.setText(_translate("w_coincidencies", "Export"))
        self.Button2PDF.setText(_translate("w_coincidencies", "PDF"))
        self.ButtonSelectFolder.setText(_translate("w_coincidencies", "Select folder"))
        self.ButDelFile.setText(_translate("w_coincidencies", "Delete"))
        self.Button2PNG.setText(_translate("w_coincidencies", "PNG"))
        self.ButtonClearFigures.setText(_translate("w_coincidencies", "Close All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("w_coincidencies", "Multiple coincidencies"))

